# Generated by Django 6.1.1 on 2026-09-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='lyrics',
            field=models.TextField(blank=True, help_text="Optional. LRC-style timed lyrics: one line per row, formatted as [mm:ss] lyric text, e.g. [0:05] Yeah... I've been tryna call"),
        ),
    ]
